### ISSUE TITLE
Thanks

### ISSUE THREAD

**Issue by mpkuse** [sezan92/self_balancing_robot#2]
Hi,
I got to know about your repo through the robotics worldwide mailing list. Thanks for it. I am actually
very new to control theory. Can you also put up good and easy to understand references for the underlying theory of PID, fuzzy and LQR. Maybe something that you use.

Much appreciated!

**Comment by sezan92** [comment]
Hello @mpkuse ! Thanks for your comments. I think this [playlist](https://www.youtube.com/watch?v=Pi7l8mMjYVE&list=PLMrJAkhIeNNR20Mz-VpzgfQs5zrYi085m) will be of great benifit for you.
